/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 94
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 13
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym__manifest_header = 2,
  sym__import_header = 3,
  sym__defs_header = 4,
  sym__commands_header = 5,
  sym__scenes_header = 6,
  anon_sym_EQ = 7,
  sym__command_item = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COLON = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_LT = 14,
  anon_sym_GT = 15,
  anon_sym_DQUOTE = 16,
  aux_sym_string_literal_token1 = 17,
  sym_escape_sequence = 18,
  sym_line_continuation = 19,
  sym_number_literal = 20,
  sym_hex_literal = 21,
  sym_type_identifier = 22,
  sym_constant_identifier = 23,
  anon_sym_DOLLAR = 24,
  anon_sym_as = 25,
  anon_sym_auto = 26,
  anon_sym_inf = 27,
  anon_sym_nan = 28,
  anon_sym_COLON_COLON = 29,
  sym_line_comment = 30,
  sym_block_comment = 31,
  sym_source_file = 32,
  sym_section = 33,
  sym_manifest_entry = 34,
  sym_import_entry = 35,
  sym_definition = 36,
  sym_scene_definition = 37,
  sym__scene_item = 38,
  sym_named_element = 39,
  sym_loadable = 40,
  sym_struct_loadable = 41,
  sym_field = 42,
  sym_tuple_loadable = 43,
  sym_simple_loadable = 44,
  sym_generic_loadable = 45,
  sym__expression = 46,
  sym__literal = 47,
  sym_string_literal = 48,
  sym_constant_usage = 49,
  sym__constant_path = 50,
  sym__as_keyword = 51,
  sym_language_constant = 52,
  sym__path_separator = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_section_repeat1 = 55,
  aux_sym_section_repeat2 = 56,
  aux_sym_section_repeat3 = 57,
  aux_sym_section_repeat4 = 58,
  aux_sym_section_repeat5 = 59,
  aux_sym_scene_definition_repeat1 = 60,
  aux_sym_struct_loadable_repeat1 = 61,
  aux_sym_string_literal_repeat1 = 62,
  aux_sym__constant_path_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym__manifest_header] = "section_header",
  [sym__import_header] = "section_header",
  [sym__defs_header] = "section_header",
  [sym__commands_header] = "section_header",
  [sym__scenes_header] = "section_header",
  [anon_sym_EQ] = "=",
  [sym__command_item] = "_command_item",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_line_continuation] = "line_continuation",
  [sym_number_literal] = "number_literal",
  [sym_hex_literal] = "hex_literal",
  [sym_type_identifier] = "type_identifier",
  [sym_constant_identifier] = "constant_identifier",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_as] = "keyword",
  [anon_sym_auto] = "auto",
  [anon_sym_inf] = "inf",
  [anon_sym_nan] = "nan",
  [anon_sym_COLON_COLON] = "::",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_section] = "section",
  [sym_manifest_entry] = "manifest_entry",
  [sym_import_entry] = "import_entry",
  [sym_definition] = "definition",
  [sym_scene_definition] = "scene_definition",
  [sym__scene_item] = "_scene_item",
  [sym_named_element] = "named_element",
  [sym_loadable] = "loadable",
  [sym_struct_loadable] = "struct_loadable",
  [sym_field] = "field",
  [sym_tuple_loadable] = "tuple_loadable",
  [sym_simple_loadable] = "simple_loadable",
  [sym_generic_loadable] = "generic_loadable",
  [sym__expression] = "_expression",
  [sym__literal] = "_literal",
  [sym_string_literal] = "string_literal",
  [sym_constant_usage] = "constant_usage",
  [sym__constant_path] = "_constant_path",
  [sym__as_keyword] = "_as_keyword",
  [sym_language_constant] = "language_constant",
  [sym__path_separator] = "PATH_SEPARATOR",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_section_repeat2] = "section_repeat2",
  [aux_sym_section_repeat3] = "section_repeat3",
  [aux_sym_section_repeat4] = "section_repeat4",
  [aux_sym_section_repeat5] = "section_repeat5",
  [aux_sym_scene_definition_repeat1] = "scene_definition_repeat1",
  [aux_sym_struct_loadable_repeat1] = "struct_loadable_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym__constant_path_repeat1] = "_constant_path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym__manifest_header] = sym__manifest_header,
  [sym__import_header] = sym__manifest_header,
  [sym__defs_header] = sym__manifest_header,
  [sym__commands_header] = sym__manifest_header,
  [sym__scenes_header] = sym__manifest_header,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym__command_item] = sym__command_item,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_line_continuation] = sym_line_continuation,
  [sym_number_literal] = sym_number_literal,
  [sym_hex_literal] = sym_hex_literal,
  [sym_type_identifier] = sym_type_identifier,
  [sym_constant_identifier] = sym_constant_identifier,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_auto] = anon_sym_auto,
  [anon_sym_inf] = anon_sym_inf,
  [anon_sym_nan] = anon_sym_nan,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_section] = sym_section,
  [sym_manifest_entry] = sym_manifest_entry,
  [sym_import_entry] = sym_import_entry,
  [sym_definition] = sym_definition,
  [sym_scene_definition] = sym_scene_definition,
  [sym__scene_item] = sym__scene_item,
  [sym_named_element] = sym_named_element,
  [sym_loadable] = sym_loadable,
  [sym_struct_loadable] = sym_struct_loadable,
  [sym_field] = sym_field,
  [sym_tuple_loadable] = sym_tuple_loadable,
  [sym_simple_loadable] = sym_simple_loadable,
  [sym_generic_loadable] = sym_generic_loadable,
  [sym__expression] = sym__expression,
  [sym__literal] = sym__literal,
  [sym_string_literal] = sym_string_literal,
  [sym_constant_usage] = sym_constant_usage,
  [sym__constant_path] = sym__constant_path,
  [sym__as_keyword] = sym__as_keyword,
  [sym_language_constant] = sym_language_constant,
  [sym__path_separator] = sym__path_separator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_section_repeat2] = aux_sym_section_repeat2,
  [aux_sym_section_repeat3] = aux_sym_section_repeat3,
  [aux_sym_section_repeat4] = aux_sym_section_repeat4,
  [aux_sym_section_repeat5] = aux_sym_section_repeat5,
  [aux_sym_scene_definition_repeat1] = aux_sym_scene_definition_repeat1,
  [aux_sym_struct_loadable_repeat1] = aux_sym_struct_loadable_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym__constant_path_repeat1] = aux_sym__constant_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__manifest_header] = {
    .visible = true,
    .named = true,
  },
  [sym__import_header] = {
    .visible = true,
    .named = true,
  },
  [sym__defs_header] = {
    .visible = true,
    .named = true,
  },
  [sym__commands_header] = {
    .visible = true,
    .named = true,
  },
  [sym__scenes_header] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym__command_item] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_line_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_auto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nan] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_manifest_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_import_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_scene_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__scene_item] = {
    .visible = false,
    .named = true,
  },
  [sym_named_element] = {
    .visible = true,
    .named = true,
  },
  [sym_loadable] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_loadable] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_loadable] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_loadable] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_loadable] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_usage] = {
    .visible = true,
    .named = true,
  },
  [sym__constant_path] = {
    .visible = false,
    .named = true,
  },
  [sym__as_keyword] = {
    .visible = false,
    .named = true,
  },
  [sym_language_constant] = {
    .visible = true,
    .named = true,
  },
  [sym__path_separator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scene_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_loadable_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__constant_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_body = 2,
  field_generic_type = 3,
  field_name = 4,
  field_path = 5,
  field_source = 6,
  field_type = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_body] = "body",
  [field_generic_type] = "generic_type",
  [field_name] = "name",
  [field_path] = "path",
  [field_source] = "source",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 2},
  [12] = {.index = 17, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 0},
  [1] =
    {field_body, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_type, 0},
  [4] =
    {field_body, 1},
    {field_name, 0},
  [6] =
    {field_alias, 2},
    {field_path, 0},
  [8] =
    {field_alias, 2},
    {field_source, 0},
  [10] =
    {field_name, 0},
    {field_value, 2},
  [12] =
    {field_path, 1},
  [13] =
    {field_type, 0},
    {field_value, 2},
  [15] =
    {field_generic_type, 2},
    {field_type, 0},
  [17] =
    {field_generic_type, 2},
    {field_type, 0},
    {field_value, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 8,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 54,
  [55] = 19,
  [56] = 54,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 57,
  [64] = 59,
  [65] = 60,
  [66] = 28,
  [67] = 22,
  [68] = 68,
  [69] = 30,
  [70] = 70,
  [71] = 33,
  [72] = 17,
  [73] = 16,
  [74] = 29,
  [75] = 32,
  [76] = 68,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 81,
  [85] = 85,
  [86] = 86,
  [87] = 80,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 83,
  [93] = 91,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 134,
        '#', 14,
        '$', 159,
        '(', 130,
        ')', 131,
        '-', 8,
        '/', 5,
        '0', 143,
        ':', 129,
        '<', 132,
        '=', 92,
        '>', 133,
        '\\', 2,
        '_', 156,
        'a', 155,
        'i', 151,
        'n', 149,
        '{', 126,
        '}', 127,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(75);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(157);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(141);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 141,
        '\r', 1,
        'u', 55,
        '"', 140,
        '\'', 140,
        '\\', 140,
        'f', 140,
        'n', 140,
        'r', 140,
        't', 140,
      );
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '"') ADVANCE(134);
      if (lookahead == '/') ADVANCE(135);
      if (lookahead == '\\') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(138);
      if (lookahead != 0) ADVANCE(139);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(134);
      if (lookahead == '/') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(167);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(168);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '0') ADVANCE(143);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(144);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(166);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(54);
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(40);
      if (lookahead == 'd') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 'm') ADVANCE(11);
      if (lookahead == 's') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(71);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(39);
      if (lookahead == 'd') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 'm') ADVANCE(11);
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(48);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(70);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'e')) ADVANCE(69);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(162);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(21);
      END_STATE();
    case 26:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 28:
      if (lookahead == 'm') ADVANCE(42);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(10);
      if (lookahead == 'h' ||
          lookahead == 'w') ADVANCE(142);
      END_STATE();
    case 30:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(12);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(142);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(164);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(160);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(70);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 42:
      if (lookahead == 'p') ADVANCE(41);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(142);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(86);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(90);
      END_STATE();
    case 48:
      if (lookahead == 's') ADVANCE(88);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(82);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 54:
      if (lookahead == 'x') ADVANCE(142);
      END_STATE();
    case 55:
      if (lookahead == '{') ADVANCE(65);
      END_STATE();
    case 56:
      if (lookahead == '}') ADVANCE(140);
      END_STATE();
    case 57:
      if (lookahead == '}') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(56);
      END_STATE();
    case 58:
      if (lookahead == '}') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 59:
      if (lookahead == '}') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 60:
      if (lookahead == '}') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 61:
      if (lookahead == '}') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 62:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(146);
      END_STATE();
    case 63:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      END_STATE();
    case 64:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(146);
      END_STATE();
    case 65:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 66:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(148);
      END_STATE();
    case 67:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(147);
      END_STATE();
    case 68:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(66);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      END_STATE();
    case 71:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(70);
      END_STATE();
    case 72:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(158);
      END_STATE();
    case 73:
      if (eof) ADVANCE(81);
      if (lookahead == '\n') SKIP(73);
      if (lookahead == '#') ADVANCE(99);
      if (lookahead == '/') ADVANCE(96);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0) ADVANCE(125);
      END_STATE();
    case 74:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 134,
        '#', 14,
        '$', 159,
        '(', 130,
        '-', 8,
        '/', 5,
        '0', 143,
        ':', 128,
        '<', 132,
        'a', 53,
        'i', 37,
        'n', 13,
        '{', 126,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(76);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(157);
      END_STATE();
    case 75:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 134,
        '#', 14,
        '$', 159,
        ')', 131,
        '-', 8,
        '/', 5,
        '0', 143,
        ':', 129,
        '=', 92,
        '>', 133,
        '_', 156,
        'a', 155,
        'i', 151,
        'n', 149,
        '}', 127,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(75);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(157);
      END_STATE();
    case 76:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 134,
        '#', 14,
        '$', 159,
        '-', 8,
        '/', 5,
        '0', 143,
        ':', 128,
        'a', 53,
        'i', 37,
        'n', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(76);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(157);
      END_STATE();
    case 77:
      if (eof) ADVANCE(81);
      ADVANCE_MAP(
        '"', 134,
        '#', 16,
        '$', 72,
        '(', 130,
        ')', 131,
        '/', 5,
        ':', 9,
        '<', 132,
        '{', 126,
        '}', 127,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(78);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 78:
      if (eof) ADVANCE(81);
      if (lookahead == '"') ADVANCE(134);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '$') ADVANCE(72);
      if (lookahead == ')') ADVANCE(131);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '}') ADVANCE(127);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(78);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 79:
      if (eof) ADVANCE(81);
      if (lookahead == '"') ADVANCE(134);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '$') ADVANCE(72);
      if (lookahead == ')') ADVANCE(131);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '_') ADVANCE(156);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(79);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(157);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 80:
      if (eof) ADVANCE(81);
      if (lookahead == '"') ADVANCE(134);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '$') ADVANCE(72);
      if (lookahead == ')') ADVANCE(131);
      if (lookahead == '/') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(157);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__manifest_header);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym__manifest_header);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__import_header);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__import_header);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__defs_header);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__defs_header);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym__commands_header);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym__commands_header);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym__scenes_header);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym__scenes_header);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '*') ADVANCE(93);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead != 0) ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '*') ADVANCE(93);
      if (lookahead != 0) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == '#') ADVANCE(99);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(125);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == '*') ADVANCE(94);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'a') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'a') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'c') ADVANCE(116);
      if (lookahead == 'd') ADVANCE(102);
      if (lookahead == 'i') ADVANCE(109);
      if (lookahead == 'm') ADVANCE(97);
      if (lookahead == 's') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'c') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'd') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'e') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'e') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'e') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'e') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'f') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'f') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'i') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'm') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'm') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'm') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'n') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'n') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'n') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'o') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'o') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'p') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 'r') ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 's') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 's') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 's') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 's') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 't') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead == 't') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym__command_item);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(166);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(137);
      if (lookahead == '/') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(139);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(136);
      if (lookahead == '/') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(137);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(137);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(135);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(138);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(139);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(139);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_line_continuation);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_number_literal);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '%') ADVANCE(142);
      if (lookahead == '.') ADVANCE(63);
      if (lookahead == 'f') ADVANCE(43);
      if (lookahead == 'p') ADVANCE(54);
      if (lookahead == 'v') ADVANCE(29);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '%') ADVANCE(142);
      if (lookahead == '.') ADVANCE(63);
      if (lookahead == 'f') ADVANCE(43);
      if (lookahead == 'p') ADVANCE(54);
      if (lookahead == 'v') ADVANCE(29);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '%') ADVANCE(142);
      if (lookahead == 'f') ADVANCE(43);
      if (lookahead == 'p') ADVANCE(54);
      if (lookahead == 'v') ADVANCE(29);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '%') ADVANCE(142);
      if (lookahead == 'f') ADVANCE(43);
      if (lookahead == 'p') ADVANCE(54);
      if (lookahead == 'v') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(146);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_hex_literal);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_hex_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(152);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(163);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(153);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(154);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_type_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(157);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_constant_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(158);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_auto);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(anon_sym_auto);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(anon_sym_inf);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_inf);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_nan);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_nan);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(156);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(167);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(2);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 74},
  [3] = {.lex_state = 74},
  [4] = {.lex_state = 74},
  [5] = {.lex_state = 74},
  [6] = {.lex_state = 74},
  [7] = {.lex_state = 74},
  [8] = {.lex_state = 74},
  [9] = {.lex_state = 74},
  [10] = {.lex_state = 74},
  [11] = {.lex_state = 74},
  [12] = {.lex_state = 74},
  [13] = {.lex_state = 77},
  [14] = {.lex_state = 77},
  [15] = {.lex_state = 77},
  [16] = {.lex_state = 79},
  [17] = {.lex_state = 79},
  [18] = {.lex_state = 74},
  [19] = {.lex_state = 77},
  [20] = {.lex_state = 77},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 80},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 77},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 77},
  [28] = {.lex_state = 80},
  [29] = {.lex_state = 80},
  [30] = {.lex_state = 80},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 80},
  [33] = {.lex_state = 80},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 77},
  [36] = {.lex_state = 77},
  [37] = {.lex_state = 77},
  [38] = {.lex_state = 77},
  [39] = {.lex_state = 77},
  [40] = {.lex_state = 77},
  [41] = {.lex_state = 77},
  [42] = {.lex_state = 73},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 73},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 74},
  [47] = {.lex_state = 73},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 77},
  [50] = {.lex_state = 77},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 77},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 77},
  [58] = {.lex_state = 77},
  [59] = {.lex_state = 77},
  [60] = {.lex_state = 77},
  [61] = {.lex_state = 77},
  [62] = {.lex_state = 77},
  [63] = {.lex_state = 77},
  [64] = {.lex_state = 77},
  [65] = {.lex_state = 77},
  [66] = {.lex_state = 77},
  [67] = {.lex_state = 77},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 77},
  [70] = {.lex_state = 77},
  [71] = {.lex_state = 77},
  [72] = {.lex_state = 77},
  [73] = {.lex_state = 77},
  [74] = {.lex_state = 77},
  [75] = {.lex_state = 77},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 77},
  [78] = {.lex_state = 77},
  [79] = {.lex_state = 77},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 74},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 77},
  [89] = {.lex_state = 77},
  [90] = {.lex_state = 77},
  [91] = {.lex_state = 74},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 74},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__manifest_header] = ACTIONS(1),
    [sym__import_header] = ACTIONS(1),
    [sym__defs_header] = ACTIONS(1),
    [sym__commands_header] = ACTIONS(1),
    [sym__scenes_header] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_line_continuation] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_hex_literal] = ACTIONS(1),
    [sym_type_identifier] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_auto] = ACTIONS(1),
    [anon_sym_inf] = ACTIONS(1),
    [anon_sym_nan] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(85),
    [sym_section] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__manifest_header] = ACTIONS(7),
    [sym__import_header] = ACTIONS(9),
    [sym__defs_header] = ACTIONS(11),
    [sym__commands_header] = ACTIONS(13),
    [sym__scenes_header] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(22), 1,
      sym_type_identifier,
    STATE(2), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 4,
      sym__scene_item,
      sym_named_element,
      sym_loadable,
      aux_sym_scene_definition_repeat1,
    STATE(46), 4,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_simple_loadable,
      sym_generic_loadable,
    ACTIONS(17), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [34] = 7,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(30), 1,
      sym_type_identifier,
    STATE(2), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(3), 4,
      sym__scene_item,
      sym_named_element,
      sym_loadable,
      aux_sym_scene_definition_repeat1,
    STATE(46), 4,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_simple_loadable,
      sym_generic_loadable,
    ACTIONS(25), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [68] = 7,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(38), 1,
      sym_type_identifier,
    STATE(2), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(3), 4,
      sym__scene_item,
      sym_named_element,
      sym_loadable,
      aux_sym_scene_definition_repeat1,
    STATE(46), 4,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_simple_loadable,
      sym_generic_loadable,
    ACTIONS(33), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [102] = 7,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(46), 1,
      sym_type_identifier,
    STATE(2), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(3), 4,
      sym__scene_item,
      sym_named_element,
      sym_loadable,
      aux_sym_scene_definition_repeat1,
    STATE(46), 4,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_simple_loadable,
      sym_generic_loadable,
    ACTIONS(41), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [136] = 7,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(5), 4,
      sym__scene_item,
      sym_named_element,
      sym_loadable,
      aux_sym_scene_definition_repeat1,
    STATE(46), 4,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_simple_loadable,
      sym_generic_loadable,
    ACTIONS(48), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [170] = 7,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      sym_type_identifier,
    ACTIONS(59), 1,
      anon_sym_DOLLAR,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      sym_number_literal,
      sym_hex_literal,
    ACTIONS(61), 3,
      anon_sym_auto,
      anon_sym_inf,
      anon_sym_nan,
    STATE(50), 8,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_generic_loadable,
      sym__expression,
      sym__literal,
      sym_string_literal,
      sym_constant_usage,
      sym_language_constant,
  [203] = 7,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      sym_type_identifier,
    ACTIONS(59), 1,
      anon_sym_DOLLAR,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(63), 2,
      sym_number_literal,
      sym_hex_literal,
    ACTIONS(61), 3,
      anon_sym_auto,
      anon_sym_inf,
      anon_sym_nan,
    STATE(87), 8,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_generic_loadable,
      sym__expression,
      sym__literal,
      sym_string_literal,
      sym_constant_usage,
      sym_language_constant,
  [236] = 7,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      sym_type_identifier,
    ACTIONS(59), 1,
      anon_sym_DOLLAR,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(65), 2,
      sym_number_literal,
      sym_hex_literal,
    ACTIONS(61), 3,
      anon_sym_auto,
      anon_sym_inf,
      anon_sym_nan,
    STATE(81), 8,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_generic_loadable,
      sym__expression,
      sym__literal,
      sym_string_literal,
      sym_constant_usage,
      sym_language_constant,
  [269] = 7,
    ACTIONS(59), 1,
      anon_sym_DOLLAR,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(69), 2,
      sym_number_literal,
      sym_hex_literal,
    ACTIONS(61), 3,
      anon_sym_auto,
      anon_sym_inf,
      anon_sym_nan,
    STATE(77), 8,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_generic_loadable,
      sym__expression,
      sym__literal,
      sym_string_literal,
      sym_constant_usage,
      sym_language_constant,
  [302] = 7,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      sym_type_identifier,
    ACTIONS(59), 1,
      anon_sym_DOLLAR,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(73), 2,
      sym_number_literal,
      sym_hex_literal,
    ACTIONS(61), 3,
      anon_sym_auto,
      anon_sym_inf,
      anon_sym_nan,
    STATE(80), 8,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_generic_loadable,
      sym__expression,
      sym__literal,
      sym_string_literal,
      sym_constant_usage,
      sym_language_constant,
  [335] = 7,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      sym_type_identifier,
    ACTIONS(59), 1,
      anon_sym_DOLLAR,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(75), 2,
      sym_number_literal,
      sym_hex_literal,
    ACTIONS(61), 3,
      anon_sym_auto,
      anon_sym_inf,
      anon_sym_nan,
    STATE(84), 8,
      sym_struct_loadable,
      sym_tuple_loadable,
      sym_generic_loadable,
      sym__expression,
      sym__literal,
      sym_string_literal,
      sym_constant_usage,
      sym_language_constant,
  [368] = 5,
    ACTIONS(79), 1,
      anon_sym_COLON_COLON,
    STATE(14), 1,
      aux_sym__constant_path_repeat1,
    STATE(88), 1,
      sym__path_separator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(77), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_constant_identifier,
  [394] = 5,
    ACTIONS(79), 1,
      anon_sym_COLON_COLON,
    STATE(15), 1,
      aux_sym__constant_path_repeat1,
    STATE(88), 1,
      sym__path_separator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(81), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_constant_identifier,
  [420] = 5,
    ACTIONS(85), 1,
      anon_sym_COLON_COLON,
    STATE(15), 1,
      aux_sym__constant_path_repeat1,
    STATE(88), 1,
      sym__path_separator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(83), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_constant_identifier,
  [446] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(88), 11,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_type_identifier,
      sym_constant_identifier,
      anon_sym_as,
  [464] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(90), 11,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_type_identifier,
      sym_constant_identifier,
      anon_sym_as,
  [482] = 5,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(92), 8,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_DQUOTE,
      sym_type_identifier,
  [506] = 5,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(100), 8,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RPAREN,
      sym_constant_identifier,
  [530] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(83), 11,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_constant_identifier,
      anon_sym_COLON_COLON,
  [548] = 5,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    STATE(36), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(26), 2,
      sym_manifest_entry,
      aux_sym_section_repeat1,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [571] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(104), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_type_identifier,
      sym_constant_identifier,
  [588] = 5,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 2,
      sym_scene_definition,
      aux_sym_section_repeat5,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [611] = 5,
    ACTIONS(108), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(24), 2,
      sym_scene_definition,
      aux_sym_section_repeat5,
    ACTIONS(106), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [634] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(111), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_constant_identifier,
  [651] = 5,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    STATE(36), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(34), 2,
      sym_manifest_entry,
      aux_sym_section_repeat1,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [674] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(115), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_constant_identifier,
  [691] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(117), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_type_identifier,
      sym_constant_identifier,
  [708] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(119), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_type_identifier,
      sym_constant_identifier,
  [725] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(121), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_type_identifier,
      sym_constant_identifier,
  [742] = 5,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(24), 2,
      sym_scene_definition,
      aux_sym_section_repeat5,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [765] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(123), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_type_identifier,
      sym_constant_identifier,
  [782] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(125), 10,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_type_identifier,
      sym_constant_identifier,
  [799] = 5,
    ACTIONS(129), 1,
      anon_sym_DQUOTE,
    STATE(36), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(34), 2,
      sym_manifest_entry,
      aux_sym_section_repeat1,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [822] = 4,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(35), 2,
      sym_import_entry,
      aux_sym_section_repeat2,
    ACTIONS(132), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [842] = 4,
    ACTIONS(139), 1,
      anon_sym_as,
    STATE(79), 1,
      sym__as_keyword,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_DQUOTE,
  [862] = 4,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(38), 2,
      sym_import_entry,
      aux_sym_section_repeat2,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [882] = 4,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(35), 2,
      sym_import_entry,
      aux_sym_section_repeat2,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [902] = 4,
    ACTIONS(143), 1,
      sym_constant_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(40), 2,
      sym_definition,
      aux_sym_section_repeat3,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [922] = 4,
    ACTIONS(147), 1,
      sym_constant_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(40), 2,
      sym_definition,
      aux_sym_section_repeat3,
    ACTIONS(145), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [942] = 4,
    ACTIONS(143), 1,
      sym_constant_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(39), 2,
      sym_definition,
      aux_sym_section_repeat3,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [962] = 5,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 1,
      sym__command_item,
    STATE(44), 1,
      aux_sym_section_repeat4,
    ACTIONS(154), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(150), 5,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [983] = 8,
    ACTIONS(7), 1,
      sym__manifest_header,
    ACTIONS(9), 1,
      sym__import_header,
    ACTIONS(11), 1,
      sym__defs_header,
    ACTIONS(13), 1,
      sym__commands_header,
    ACTIONS(15), 1,
      sym__scenes_header,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(45), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [1010] = 5,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 1,
      sym__command_item,
    STATE(47), 1,
      aux_sym_section_repeat4,
    ACTIONS(154), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(158), 5,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [1031] = 8,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
    ACTIONS(164), 1,
      sym__manifest_header,
    ACTIONS(167), 1,
      sym__import_header,
    ACTIONS(170), 1,
      sym__defs_header,
    ACTIONS(173), 1,
      sym__commands_header,
    ACTIONS(176), 1,
      sym__scenes_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(45), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [1058] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(179), 8,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_DQUOTE,
      sym_type_identifier,
  [1073] = 5,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    ACTIONS(185), 1,
      sym__command_item,
    STATE(47), 1,
      aux_sym_section_repeat4,
    ACTIONS(154), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(183), 5,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
  [1094] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(188), 7,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      anon_sym_DQUOTE,
  [1108] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(190), 7,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      sym_identifier,
  [1122] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(192), 7,
      ts_builtin_sym_end,
      sym__manifest_header,
      sym__import_header,
      sym__defs_header,
      sym__commands_header,
      sym__scenes_header,
      sym_constant_identifier,
  [1136] = 4,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(154), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(196), 3,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
      sym_line_continuation,
  [1152] = 4,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    STATE(56), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(154), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(201), 3,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
      sym_line_continuation,
  [1168] = 4,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
    STATE(54), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(154), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(205), 3,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
      sym_line_continuation,
  [1184] = 4,
    ACTIONS(207), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(154), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(209), 3,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
      sym_line_continuation,
  [1200] = 5,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    ACTIONS(213), 1,
      anon_sym_LPAREN,
    ACTIONS(215), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1218] = 4,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(154), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(209), 3,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
      sym_line_continuation,
  [1234] = 4,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_field,
      aux_sym_struct_loadable_repeat1,
  [1249] = 4,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_field,
      aux_sym_struct_loadable_repeat1,
  [1264] = 4,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(60), 2,
      sym_field,
      aux_sym_struct_loadable_repeat1,
  [1279] = 4,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_field,
      aux_sym_struct_loadable_repeat1,
  [1294] = 4,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(57), 2,
      sym_field,
      aux_sym_struct_loadable_repeat1,
  [1309] = 4,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(63), 2,
      sym_field,
      aux_sym_struct_loadable_repeat1,
  [1324] = 4,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_field,
      aux_sym_struct_loadable_repeat1,
  [1339] = 4,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(65), 2,
      sym_field,
      aux_sym_struct_loadable_repeat1,
  [1354] = 4,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_field,
      aux_sym_struct_loadable_repeat1,
  [1369] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1378] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(104), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1387] = 3,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1398] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(121), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1407] = 3,
    ACTIONS(246), 1,
      sym_identifier,
    STATE(27), 1,
      sym__constant_path,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1418] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(125), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1427] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(90), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1436] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(88), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1445] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(119), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1454] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(123), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1463] = 3,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1474] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(252), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1483] = 3,
    ACTIONS(254), 1,
      anon_sym_as,
    STATE(89), 1,
      sym__as_keyword,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1494] = 2,
    ACTIONS(256), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1502] = 2,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1510] = 2,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1518] = 2,
    ACTIONS(262), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1526] = 2,
    ACTIONS(264), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1534] = 2,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1542] = 2,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1550] = 2,
    ACTIONS(270), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1558] = 2,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1566] = 2,
    ACTIONS(274), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1574] = 2,
    ACTIONS(276), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1582] = 2,
    ACTIONS(278), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1590] = 2,
    ACTIONS(280), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1598] = 2,
    ACTIONS(282), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1606] = 2,
    ACTIONS(284), 1,
      sym_type_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 102,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 170,
  [SMALL_STATE(8)] = 203,
  [SMALL_STATE(9)] = 236,
  [SMALL_STATE(10)] = 269,
  [SMALL_STATE(11)] = 302,
  [SMALL_STATE(12)] = 335,
  [SMALL_STATE(13)] = 368,
  [SMALL_STATE(14)] = 394,
  [SMALL_STATE(15)] = 420,
  [SMALL_STATE(16)] = 446,
  [SMALL_STATE(17)] = 464,
  [SMALL_STATE(18)] = 482,
  [SMALL_STATE(19)] = 506,
  [SMALL_STATE(20)] = 530,
  [SMALL_STATE(21)] = 548,
  [SMALL_STATE(22)] = 571,
  [SMALL_STATE(23)] = 588,
  [SMALL_STATE(24)] = 611,
  [SMALL_STATE(25)] = 634,
  [SMALL_STATE(26)] = 651,
  [SMALL_STATE(27)] = 674,
  [SMALL_STATE(28)] = 691,
  [SMALL_STATE(29)] = 708,
  [SMALL_STATE(30)] = 725,
  [SMALL_STATE(31)] = 742,
  [SMALL_STATE(32)] = 765,
  [SMALL_STATE(33)] = 782,
  [SMALL_STATE(34)] = 799,
  [SMALL_STATE(35)] = 822,
  [SMALL_STATE(36)] = 842,
  [SMALL_STATE(37)] = 862,
  [SMALL_STATE(38)] = 882,
  [SMALL_STATE(39)] = 902,
  [SMALL_STATE(40)] = 922,
  [SMALL_STATE(41)] = 942,
  [SMALL_STATE(42)] = 962,
  [SMALL_STATE(43)] = 983,
  [SMALL_STATE(44)] = 1010,
  [SMALL_STATE(45)] = 1031,
  [SMALL_STATE(46)] = 1058,
  [SMALL_STATE(47)] = 1073,
  [SMALL_STATE(48)] = 1094,
  [SMALL_STATE(49)] = 1108,
  [SMALL_STATE(50)] = 1122,
  [SMALL_STATE(51)] = 1136,
  [SMALL_STATE(52)] = 1152,
  [SMALL_STATE(53)] = 1168,
  [SMALL_STATE(54)] = 1184,
  [SMALL_STATE(55)] = 1200,
  [SMALL_STATE(56)] = 1218,
  [SMALL_STATE(57)] = 1234,
  [SMALL_STATE(58)] = 1249,
  [SMALL_STATE(59)] = 1264,
  [SMALL_STATE(60)] = 1279,
  [SMALL_STATE(61)] = 1294,
  [SMALL_STATE(62)] = 1309,
  [SMALL_STATE(63)] = 1324,
  [SMALL_STATE(64)] = 1339,
  [SMALL_STATE(65)] = 1354,
  [SMALL_STATE(66)] = 1369,
  [SMALL_STATE(67)] = 1378,
  [SMALL_STATE(68)] = 1387,
  [SMALL_STATE(69)] = 1398,
  [SMALL_STATE(70)] = 1407,
  [SMALL_STATE(71)] = 1418,
  [SMALL_STATE(72)] = 1427,
  [SMALL_STATE(73)] = 1436,
  [SMALL_STATE(74)] = 1445,
  [SMALL_STATE(75)] = 1454,
  [SMALL_STATE(76)] = 1463,
  [SMALL_STATE(77)] = 1474,
  [SMALL_STATE(78)] = 1483,
  [SMALL_STATE(79)] = 1494,
  [SMALL_STATE(80)] = 1502,
  [SMALL_STATE(81)] = 1510,
  [SMALL_STATE(82)] = 1518,
  [SMALL_STATE(83)] = 1526,
  [SMALL_STATE(84)] = 1534,
  [SMALL_STATE(85)] = 1542,
  [SMALL_STATE(86)] = 1550,
  [SMALL_STATE(87)] = 1558,
  [SMALL_STATE(88)] = 1566,
  [SMALL_STATE(89)] = 1574,
  [SMALL_STATE(90)] = 1582,
  [SMALL_STATE(91)] = 1590,
  [SMALL_STATE(92)] = 1598,
  [SMALL_STATE(93)] = 1606,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_element, 1, 0, 3),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_named_element, 1, 0, 3), SHIFT(52),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_named_element, 1, 0, 3), SHIFT(18),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scene_definition_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scene_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scene_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_element, 2, 0, 5),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_named_element, 2, 0, 5), SHIFT(52),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_named_element, 2, 0, 5), SHIFT(18),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scene_definition, 2, 0, 5),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_scene_definition, 2, 0, 5), SHIFT(52),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scene_definition, 1, 0, 3),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_scene_definition, 1, 0, 3), SHIFT(52),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__constant_path, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__constant_path, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__constant_path_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__constant_path_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_loadable, 1, 0, 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_loadable, 7, 0, 12),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat5, 2, 0, 0),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat5, 2, 0, 0), SHIFT_REPEAT(52),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_language_constant, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_usage, 2, 0, 9),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_loadable, 3, 0, 4),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_loadable, 4, 0, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_loadable, 4, 0, 10),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_loadable, 6, 0, 11),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_loadable, 7, 0, 11),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat2, 2, 0, 0),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat2, 2, 0, 0), SHIFT_REPEAT(78),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_manifest_entry, 1, 0, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat3, 2, 0, 0),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat3, 2, 0, 0), SHIFT_REPEAT(86),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 2, 0, 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loadable, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat4, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_repeat4, 2, 0, 0),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat4, 2, 0, 0), SHIFT_REPEAT(47),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_manifest_entry, 3, 0, 6),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_entry, 3, 0, 7),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, 0, 8),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_loadable_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_loadable_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 8),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [268] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__path_separator, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cobweb(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cobweb",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
